version: "3.9"

services:
  api-woods:
    build:
      context: .
      dockerfile: ./DockerFile
    ports:
    - "8000:8000"
    volumes:
      - ./media:/app/media
    logging:
      options:
        max-size: 50m
    depends_on:
      db-woods:
        condition: service_healthy


  db-woods:
    image: postgres:15
    container_name: db-woods
    env_file: ./.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      options:
        max-size: 50m
    volumes:
      - ./pg-data:/var/lib/postgresql/data
