# Generated by Django 5.0.1 on 2024-01-28 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание категории')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Заголовок категории')),
                ('image', models.ImageField(upload_to='images/category/', verbose_name='Фото категории')),
                ('number_on_main_page', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер на первой странице')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата время заказа')),
                ('description', models.TextField(verbose_name='Текст заказа')),
                ('contact', models.TextField(verbose_name='Контакты')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к заказу')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название фото')),
                ('image', models.ImageField(upload_to='images/all/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
        migrations.CreateModel(
            name='SliderAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название атрибута слайдера')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок атрибута слайдера')),
                ('description', models.TextField(verbose_name='Описание слайдера')),
                ('start_value', models.PositiveIntegerField(default=0, verbose_name='Начальное значение слайдера')),
                ('stop_value', models.PositiveIntegerField(default=100, verbose_name='Конечное значение слайдера')),
            ],
            options={
                'verbose_name': 'Атрибут слайдер',
                'verbose_name_plural': 'Атрибуты слайдер',
            },
        ),
        migrations.CreateModel(
            name='MainAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название атрибута')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок атрибута')),
                ('additional_price', models.FloatField(default=0.0, verbose_name='Добавленная цена')),
                ('thumbnail', models.ImageField(upload_to='images/attribute/', verbose_name='Логотип атрибута (мини)')),
                ('vendor_code', models.CharField(max_length=50, verbose_name='Артикул товара с атрибутом')),
                ('item_photos', models.ManyToManyField(to='catalog.photo', verbose_name='Фото товара с атрибутом')),
            ],
            options={
                'verbose_name': 'Атрибут',
                'verbose_name_plural': 'Атрибуты',
            },
        ),
        migrations.CreateModel(
            name='CategoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название товара')),
                ('description', models.TextField(verbose_name='Описание товара')),
                ('price', models.FloatField(default=0.0, verbose_name='Цена')),
                ('vendor_code', models.CharField(max_length=50, verbose_name='Артикул товара')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.category', verbose_name='Категория')),
                ('main_attribute', models.ManyToManyField(blank=True, related_name='category_items', to='catalog.mainattribute', verbose_name='Основной атрибут')),
                ('item_photos', models.ManyToManyField(blank=True, to='catalog.photo', verbose_name='Фото товара')),
                ('slider', models.ManyToManyField(blank=True, related_name='category_items', to='catalog.sliderattribute', verbose_name='Слайдер атрибут')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('id',),
            },
        ),
    ]
